name: Ejecutar pruebas con Pytest

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Pytest
        run: pytest
